# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'

target 'ViroSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViroSample
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'ViroSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ViroSample-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViroSample-tvOS

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
